### ISSUE TITLE
Can't connect to zendesk chat on android

### ISSUE THREAD

**Issue by deounix** [witalobenicio/react-native-zendesk-chat-api#2]
I get my account key from chat dashboard --> check connection --> Account Key

```
      ZendeskChatApi.startChat(
        "xxxxxxxxxxxxxxxxxxxxxx",
        userInfo,
        chatConfig
      );

      ZendeskChatApi.addChatTimeoutObserver((timeout) => {
        console.log("timeout: ", timeout);
      });

      ZendeskChatApi.isChatAvailable((chatStatus) => {
        console.log("chatAvailable", chatStatus);
        ZendeskChatApi.sendMessage("Hi there");
      });

      ZendeskChatApi.isOnline((chatStatus) => {
        console.log("chatStatus", chatStatus);
        ZendeskChatApi.sendMessage("Hi there");
      });

      ZendeskChatApi.addChatConnectionObserver((status) => {
        console.log("Connect status is: ", status);
      });
```

Output:

```
ReactNativeJS: 'Connect status is: ', { status: 'disconnected' }
ReactNativeJS: 'chatAvailable', true
ReactNativeJS: 'chatStatus', 'OFFLINE'
```

**Comment by witalobenicio** [comment]
@deounix you need to wait until your status is ONLINE or online (case sensitive).
If your chat is permanently offline, you may check if your Zendesk Chat (agent) is open and has some user/department online.

**Comment by deounix** [comment]
@witalobenicio thank it works now after cleaning the build.

I've another question on Android when I'm using sone image picker that returned the path as (content://) the sendFile function works 100% but when the path will be (file:///) the sendFile will not work

eg:  file:///storage/emulated/0/Pictures/de979eb1-2d70-4bca-ac07-475a3d991b8c.jpg

I think it would be better to add a callback to sendFile

```
            if (file.exists()) {
                chatApi.send(file);
                callback(true);
            } else {
                Log.d("FILE", "FILE DOESNT EXISTS");
                callback("file doesn't exists.")
            }
```

**Comment by witalobenicio** [comment]
@deounix I've updated the documentation about sending a file. Please take a look.
I'll close this issue.
