### ISSUE TITLE
Can't release the app on apple store

### ISSUE THREAD

**Issue by deounix** [witalobenicio/react-native-zendesk-chat-api#3]
```
ITMS-90809: Deprecated API Usage - Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.
```

I searched for "UIWebView" and I find it in the binary

```
grep -rnw "." -e "UIWebView"

Binary file ./node_modules/rn-zendesk-chat-api/ios/ZDCChatAPI.framework/ZDCChatAPI matches
Binary file ./node_modules/rn-zendesk-chat-api/ios/ZDCChat.framework/ZDCChat matches
```

**Comment by deounix** [comment]
I found this explain my case: https://develop.zendesk.com/hc/en-us/articles/360035447713-Zendesk-policy-on-the-deprecation-of-UIWebView

But the app is auto removed after release I think from this error: 
`
ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.`

**Comment by witalobenicio** [comment]
@deounix  Probably Zendesk still uses UIWebView to make their requests. They use web view for sure, but I didn't know that they use a very old version.
I need to check if they have a new version of the SDK that changes UIWebView to WKWebView.
If they don't have, it won't be possible, unfortunately. 
If you want, you can check that and open a PR.

**Comment by witalobenicio** [comment]
@deounix I just saw that Zendesk released their Chat SDK v2, but right now, I'm not able to make those updates.
As soon as I can, I'll try to do that. But again, if you can, you can solve and open a PR.

**Comment by deounix** [comment]
@witalobenicio thank you I'll try to update to sdk 2.

But how do you use ios without Pods?

I'm trying to build without adding ZDChat to pods and getting these errors:


```
Showing Recent Issues
Could not find or use auto-linked framework 'ZDCChatAPI'

Could not find or use auto-linked framework 'ZDCChat'

Undefined symbol: _OBJC_CLASS_$_ZDCAPIConfig

Undefined symbol: _OBJC_CLASS_$_ZDCChat

Undefined symbol: _OBJC_CLASS_$_ZDCChatAPI

Undefined symbol: _OBJC_CLASS_$_ZDCVisitorInfo
```

So I removed both (ZDChat.framework) and (ZDChatApi.framework) and setting them manually in Pods folder and it works but then this error happens when releasing to the apple store

`ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.`

How do you build this without Pods?

**Comment by deounix** [comment]
```
ld: warning: Could not find or use auto-linked framework 'ZDCChatAPI'
ld: warning: Could not find or use auto-linked framework 'ZDCChat'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ZDCAPIConfig", referenced from:
      objc-class-ref in libZendeskChat.a(ZendeskChat.o)
  "_OBJC_CLASS_$_ZDCChat", referenced from:
      objc-class-ref in libZendeskChat.a(ZendeskChat.o)
  "_OBJC_CLASS_$_ZDCChatAPI", referenced from:
      objc-class-ref in libZendeskChat.a(ZendeskChat.o)
  "_OBJC_CLASS_$_ZDCVisitorInfo", referenced from:
      objc-class-ref in libZendeskChat.a(ZendeskChat.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by witalobenicio** [comment]
@deounix I'm using React Native 0.59.9.
In the docs I explai how to use. Maybe using .xcworkspace it's different from .xcproject.

**Comment by witalobenicio** [comment]
@deounix maybe you could look for "How to use iOS lib without pods with cxworkspace".

**Comment by witalobenicio** [comment]
@deounix maybe this link will help you:

https://medium.com/@akfreas/how-to-use-cocoapods-with-your-internal-ios-frameworks-192aa472f64b

**Comment by deounix** [comment]
@witalobenicio sorry for late. none of them works I'm also using react-native 0.59.10

try to create a new react-native project and install your plugin

```
react-native init test --version 0.59.10
yarn add rn-zendesk-chat-api
react-native link rn-zendesk-chat-api
```

But I can't build it.

**Comment by deounix** [comment]
@witalobenicio using pods I installed 'ZDCChat' and remove it from ur plugin it works 100% in the simulator but when releasing the app the (ZDCChat) framework not included inside the app so I get this error

`ITMS-90562: Invalid Bundle - One or more dynamic libraries that are referenced by your app are not present in the dylib search path.`

**Comment by deounix** [comment]
@witalobenicio how I checked if the framework is included or not.

after archiving I get build name like (test 4-29-20, 8.19 AM.xcarchive) I rename it to (test 4-29-20, 8.19 AM.xcarchive.zip)

```
cd test 4-29-20, 8.19 AM.xcarchive.zip
cd Products/Applications/Test.app/

# this command will list all ur frameworks inside the app
otool -L Test
```

And I can't find both the ZDCChat & the ZDCChatApi frameworks

**Comment by witalobenicio** [comment]
@deounix using RN 0.59.10 what errors do you get?
You shouldn't install any pods with RN 0.59.10.

**Comment by witalobenicio** [comment]
@deounix Have you been able to build it?

If you are using RN >= 0.60 you should just install the lib with yarn or npm and then goes to iOS folder and run pod install.

If you are using RN < 0.60 you should link the library (presuming you are not using pods)
